kind: pipeline
type: docker
name: build

trigger:
  event:
    - tag

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    environment:
      CACHE_TAG: 'build'
    settings:
      restore: true
      cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME, CACHE_TAG]
      mount:
        - ./vendor
    volumes:
      - name: cache
        path: /cache

  - name: composer
    image: composer:2
    commands:
      - composer install --ignore-platform-reqs --no-interaction
    depends_on:
      - restore-cache

  - name: build
    image: php:8.1-alpine
    commands:
      - php application app:build --build-version=${DRONE_TAG}
    depends_on:
      - composer

  - name: build-docker-image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: ./docker/Dockerfile
      repo: an0r4k0/representative-reward-distribution
      tags:
        - latest
        - ${DRONE_TAG}
    depends_on:
      - build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    environment:
      CACHE_TAG: 'build'
    settings:
      rebuild: true
      cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME, CACHE_TAG]
      mount:
        - ./vendor
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - composer

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
